from __future__ import annotations
import asyncio
import time
from typing import Optional
import numpy as np

from ...src.utils.config_loader import get_settings
from ...src.logger import GLOBAL_LOGGER as logger
from ...src.exception.custom_exception import MulitagentragException
from ...src.models.models import (
    AgentEvent, AgentStatus, RerankedChunk)
from ...src.utils.general_utils import _timed_event
from ...src.llm.llms import BaseLLMClient, LLMResponse, get_llm_client

settings= get_settings()
class AnswerGeneratorAgent:
    """
    Generates answer based on the validated retrieved. A single LLM call with a
    structured system prompt emphasising grounded, citation_based, and refusal to 
    speculate beyond provided sources

    """

    NAME = "AnswerGenerator"
    SYSTEM_PROMPT = """You are a precise, citation-grounded 
                question-answering assistant
                
                Rules you MUST follow:
                1. Answer only from the provided context passages.
                2. If the answer is not in the context, say: "The provided sources do not contain enough information to answer this question."
                3. Do NOT invent facts, statistics, names, or dates not present in the sources.
                4. Reference source numbers (e.g. [1], [2]) inline when using that source.
                5. Keep the answer concise: 2-4 sentences for simple questions, structured paragraphs for complex ones.
                6. Never Start with "Based on the context" - be direct.
                """
    
    def __init__(self, llm: Optional[BaseLLMClient]=None, agent_id:int=0):
        self.llm = llm or get_llm_client()
        self.agent_id = agent_id
        self.agent_name = f"{self.NAME}-{agent_id}"

    async def run(self,
            query:str, chunks:list[RerankedChunk], 
            temperature: Optional[float]=None,
            )-> tuple[str, AgentEvent]:
        
        try:
            t0= time.perf_counter()

            if not chunks:
                msg= "The Provided sources do not contain enough information to answer this question."
                return msg, _timed_event(agent=self.agent_name, status=AgentStatus.DONE, message=msg,
                                         start=t0,)
            
            context_parts =[]
            for i, rc in enumerate(chunks,1):
                context_parts.append(
                f"[{i}] {rc.chunk.content.strip()}")

            context_str = "\n".join(context_parts)
            user_content = f"Context:\n{context_str}\n\nQuestion: {query}"

            # Vary the temperature per agent for ensemble when a base temperature is provided.
            # If no temperature is provided, let the LLM client use its default.
            temp = (temperature + self.agent_id * 0.05) if temperature is not None else None

            resp: LLMResponse = await self.llm.complete(
                system=self.SYSTEM_PROMPT, user = user_content, 
                temperature=temp,
            )
            msg = f"Generated answer ({resp.output_tokens} tokens)"
            event = _timed_event(
                agent=self.agent_name, status=AgentStatus.DONE, message=msg,
                start= t0, tokens = resp.total_tokens, llm_latency_ms=resp.latency_ms,
            )
            logger.info("Answer Generated by the LLM")
            return resp.text.strip(), event

        except Exception as e:
            logger.error("Answer Generation failed", agent=self.NAME, error=str(e))
            raise MulitagentragException(f"Unable to generate answer due LLM error", error_details=str(e))
